apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: label-viewer-postgres-data
  labels:
    app: label-viewer
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
