apiVersion: v1
kind: Service
metadata:
  name: label-viewer
  labels:
    app: label-viewer
spec:
  type: NodePort
  selector:
    app: label-viewer
  ports:
    - name: http
      port: 8765
      targetPort: http
      nodePort: 30920
